-- Active: 1731564887736@@127.0.0.1@3306@relationship
--users table
CREATE TABLE  `users`(
    `id` BIGINT(30) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `firstname` VARCHAR(50) NOT NULL ,
    `lastname` VARCHAR(50) NOT NULL ,
    `email` VARCHAR(50) NOT NULL ,
    `mobile` VARCHAR(50) NOT NULL ,
    `password` VARCHAR(50) NOT NULL ,
    `otp` VARCHAR(50) NOT NULL ,
    `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
)

--catagories table 
 CREATE TABLE `categories`(
    `id` BIGINT(30) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL ,
    `user_id` BIGINT(50) UNSIGNED NOT NULL,
    `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
     Foreign Key (`user_id`) REFERENCES `users`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
 )

--customer table 
 CREATE TABLE `customers`(
    `id` BIGINT(30) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL ,
    `email`VARCHAR(50) NOT NULL,
    `mobile` VARCHAR(50) NOT NULL,
    `user_id` BIGINT(50) UNSIGNED NOT NULL,
    `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
     Foreign Key (`user_id`) REFERENCES `users`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
 )

-- product table
  CREATE TABLE `product`(
    `id` BIGINT(30) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL ,
    `price`VARCHAR(50) NOT NULL,
    `unit` VARCHAR(50) NOT NULL,
    `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    `user_id` BIGINT(50) UNSIGNED NOT NULL,
    `category_id` BIGINT(50) UNSIGNED NOT NULL,
     Foreign Key (`user_id`) REFERENCES `users`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
     FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
 )

 --invoice table 
   CREATE TABLE `invoice`(
     `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT  PRIMARY KEY,
    `total` VARCHAR(20) NOT NULL,
    `discount` VARCHAR(20) NOT NULL,
    `vat` VARCHAR(20) NOT NULL,
    `payable` VARCHAR(20) NOT NULL,
    `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    `user_id` BIGINT(50) UNSIGNED NOT NULL,
    `customer_id` BIGINT(50) UNSIGNED NOT NULL,
    Foreign Key (`user_id`) REFERENCES `users`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
   )

    --invoice table 
   CREATE TABLE `invoiceProduct`(
     `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT  PRIMARY KEY,
    `qty` VARCHAR(20) NOT NULL,
    `sale_price` VARCHAR(20) NOT NULL,
    `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    `user_id` BIGINT(50) UNSIGNED NOT NULL,
    `product_id` BIGINT(50) UNSIGNED NOT NULL,
    `invoice_id` BIGINT(50) UNSIGNED NOT NULL,
    Foreign Key (`user_id`) REFERENCES `users`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`product_id`) REFERENCES `product`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (`invoice_id`) REFERENCES `invoice`(`id`) ON UPDATE CASCADE ON DELETE RESTRICT
   )
   