
 SELECT SUM('AVAIL_BALANCE'),`CUST_ID`,`OPEN_BRANCH_ID` FROM `account` GROUP BY  `CUST_ID`,'OPEN_BRANCH_ID' ;

SELECT `CUST_ID`, SUM(`ACCOUNT_ID`) as total  FROM `account` GROUP BY `CUST_ID` HAVING total > 5000;